# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sweet_cash.integrations.proto import user_pb2 as sweet__cash_dot_integrations_dot_proto_dot_user__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sweet_cash/integrations/proto/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/grpc.UserService/CreateUser',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/grpc.UserService/UpdateUser',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.ConfirmUser = channel.unary_unary(
                '/grpc.UserService/ConfirmUser',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.ConfirmUserRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.ConfirmUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/grpc.UserService/DeleteUser',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/grpc.UserService/GetUserById',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByIdRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByIdResponse.FromString,
                _registered_method=True)
        self.GetUsersByIds = channel.unary_unary(
                '/grpc.UserService/GetUsersByIds',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUsersByIdsRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUsersByIdsResponse.FromString,
                _registered_method=True)
        self.GetUserByEmail = channel.unary_unary(
                '/grpc.UserService/GetUserByEmail',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByEmailResponse.FromString,
                _registered_method=True)
        self.VerifyPassword = channel.unary_unary(
                '/grpc.UserService/VerifyPassword',
                request_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.VerifyPasswordRequest.SerializeToString,
                response_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.VerifyPasswordResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.UpdateUserRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.UpdateUserResponse.SerializeToString,
            ),
            'ConfirmUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmUser,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.ConfirmUserRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.ConfirmUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.DeleteUserRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.DeleteUserResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByIdRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByIdResponse.SerializeToString,
            ),
            'GetUsersByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersByIds,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUsersByIdsRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUsersByIdsResponse.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByEmailResponse.SerializeToString,
            ),
            'VerifyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPassword,
                    request_deserializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.VerifyPasswordRequest.FromString,
                    response_serializer=sweet__cash_dot_integrations_dot_proto_dot_user__pb2.VerifyPasswordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/CreateUser',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.CreateUserRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/UpdateUser',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.UpdateUserRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/ConfirmUser',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.ConfirmUserRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.ConfirmUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/DeleteUser',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.DeleteUserRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/GetUserById',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByIdRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/GetUsersByIds',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUsersByIdsRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUsersByIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/GetUserByEmail',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.GetUserByEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.UserService/VerifyPassword',
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.VerifyPasswordRequest.SerializeToString,
            sweet__cash_dot_integrations_dot_proto_dot_user__pb2.VerifyPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
